types:
  feat: "Features"
  fix: "Bug Fixes"
  chore: "Miscellaneous"
scopes:
  auto: [dotnet, go, java, nodejs, python, yaml]
  backend: [diy, service]
  build: []
  ci: []
  cli:
    - about
    - config
    - display
    - engine
    - env
    - import
    - install
    - new
    - plugin
    - package
    - state
  components: [dotnet, go, java, nodejs, python, yaml]
  docs: []
  engine: []
  pkg: [testing]
  programgen: [dotnet, go, java, nodejs, python, yaml]
  protobuf: []
  sdk: [dotnet, go, java, nodejs, python, yaml]
  sdkgen: [dotnet, go, java, nodejs, python, yaml, docs]
  yaml: []
