[tools]
github-cli = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
go = "1.24"
gofumpt = "latest"
golangci-lint = "2.6.2"
jq = "latest"
node = "20"
"npm:pnpm" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yarn" = "latest"
bun = "latest"
python = '3.11'
uv = "0.10.0"
"go:github.com/mitranim/gow" = "latest"
"go:go.abhg.dev/requiredfield/cmd/requiredfield" = "0.7.1"
"github:WebAssembly/wabt" = "1.0.37"
dotnet = "8"

[plugins]
