[[constraint]]
  name = "github.com/Nvveen/Gotty"
  revision = "a8b993ba6abdb0e0c12b0125c603323a71c7790c"
  source = "https://github.com/ijc25/Gotty"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[[override]]
  name = "github.com/xanzy/ssh-agent"
  version = "v0.2.0"

[[override]]
  name = "github.com/golang/glog"
  source = "github.com/pulumi/glog"
  branch = "pulumi-master"
