name: Test Docs Generation

on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "GitHub ref to use"
        type: string
      pull_request_number:
        required: true
        description: "Pull request number"
        type: string
      pull_request_author:
        required: true
        description: "Pull request author, as a login name"
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  DOTNET_ROLL_FORWARD: "Major"

permissions:
  contents: read

jobs:
  aws:
    name: Resource Docs
    # Verify that the event is not triggered by a fork since forks cannot
    # access secrets other than the default GITHUB_TOKEN. Specifically,
    # this workflow relies on the secret PULUMI_BOT_GH_PAT_DOCS to create a
    # draft PR in the docs repo.
    env:
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x # TODO(friel) use version_set
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x # TODO(friel) use version_set
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.x # TODO(friel) use version_set
      - name: Set up DotNet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # TODO(friel) use version_set
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          path: pulumi
          ref: ${{ inputs.ref }}
          token: ${{ secrets.PULUMI_BOT_GH_PAT_DOCS }}
      - name: Check out pulumi-aws
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-aws
          path: pulumi-aws
          token: ${{ secrets.PULUMI_BOT_GH_PAT_DOCS }}
      - name: Check out pulumi-kubernetes
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-kubernetes
          path: pulumi-kubernetes
          token: ${{ secrets.PULUMI_BOT_GH_PAT_DOCS }}
      - name: Check out docs
        uses: actions/checkout@v2
        with:
          # Use the PAT and not the default GITHUB_TOKEN since we want to create a branch
          # in this workflow and push it to a remote that is NOT the current repo, i.e. pulumi/pulumi.
          token: ${{ secrets.PULUMI_BOT_GH_PAT_DOCS }}
          repository: pulumi/docs
          path: docs

      - name: Regenerate resource docs
        id: regenerate-resource-docs
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          BRANCH_NAME="${GITHUB_ACTOR}/${PR_NUMBER}-test-generator-changes"

          # If generating docs for more providers here, be sure to update
          # the description of the draft PR that is opened in the next step.
          pushd docs

          pushd tools/resourcedocsgen
          go mod edit -replace github.com/pulumi/pulumi/pkg/v3=../../../pulumi/pkg
          go mod edit -replace github.com/pulumi/pulumi/sdk/v3=../../../pulumi/sdk
          popd

          ./scripts/gen_resource_docs.sh aws true
          ./scripts/gen_resource_docs.sh kubernetes true

          # Undo the changes to the go.mod and go.sum files since we don't want the PR
          # to contain local overrides or the PR build in docs repo would fail.
          pushd tools/resourcedocsgen
          git checkout .
          popd

          popd

          echo "::set-output name=branchName::${BRANCH_NAME}"
          echo "::set-output name=prNumber::${PR_NUMBER}"

      - name: Create draft docs PR
        uses: peter-evans/create-pull-request@v3
        with:
          draft: true
          # We use a repo:public scoped PAT instead of the implicitly provided GITHUB_TOKEN secret here
          # because we want the creation of the docs PR to trigger the `on: pull_request` workflow in the
          # docs repo. Using a fork repo to raise the PR would also cause the `on: pull_request` workflow
          # to trigger, but currently Pulumify in the docs repo does not run for forks, but we want it to
          # generate the preview link.
          token: ${{ secrets.PULUMI_BOT_GH_PAT_DOCS }}
          path: docs
          committer: Pulumi Bot <bot@pulumi.com>
          author: Pulumi Bot <bot@pulumi.com>
          commit-message: Regenerate resource docs
          title: Preview resource docs changes for pulumi/pulumi#${{ steps.regenerate-resource-docs.outputs.prNumber }}
          body: |
            This PR was auto-generated from pulumi/pulumi#${{ steps.regenerate-resource-docs.outputs.prNumber }}.
            By default, this PR contains regenerated docs for AWS and Kubernetes only.
            After review, this PR should be manually closed.
          # Assign the draft PR to the author of the current PR.
          assignees: ${{ inputs.pull_request_author }}
          branch: ${{ steps.regenerate-resource-docs.outputs.branchName }}
