name: Downstream Codegen Tests
on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "GitHub ref to use"
        type: string
      pull_request_number:
        required: true
        description: "Pull request number"
        type: string

env:
  DOTNET_ROLL_FORWARD: "Major"

permissions:
  contents: read

jobs:
  downstream-test:
    name: Test ${{ matrix.provider }} Downstream
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ["aws", "gcp", "azure", "azuread", "random", "kubernetes"]
      fail-fast: false
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
          check-latest: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
        with:
          repo: pulumi/pulumictl
          tag: v0.0.32
          cache: enable
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: pulumi/pulumi-terraform-bridge
          ref: master
          path: ./pulumi-terraform-bridge
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@v1.0.0
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
          replacements: github.com/pulumi/pulumi/pkg/v3=pulumi/pkg,github.com/pulumi/pulumi/sdk/v3=pulumi/sdk,github.com/pulumi/pulumi-terraform-bridge/v3=pulumi/pulumi-terraform-bridge
          downstream-name: pulumi-${{ matrix.provider }}
          downstream-url: https://github.com/pulumi/pulumi-${{ matrix.provider }}
          use-provider-dir: true
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
