name: Downstream Codegen Tests
on:
  pull_request:
    paths:
    - 'pkg/codegen/**'
    - '.github/workflows/codegen-test.yml'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  downstream-aws:
    name: Test AWS Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-aws
          downstream-url: https://github.com/pulumi/pulumi-aws
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}
          use-provider-dir: true

  downstream-azure:
    name: Test Azure Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-azure
          downstream-url: https://github.com/pulumi/pulumi-azure
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}
          use-provider-dir: true

  downstream-gcp:
    name: Test GCP Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-gcp
          downstream-url: https://github.com/pulumi/pulumi-gcp
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}
          use-provider-dir: true

  downstream-azuread:
    name: Test AzureAD Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-azuread
          downstream-url: https://github.com/pulumi/pulumi-azuread
          use-provider-dir: true
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}

  downstream-random:
    name: Test Random Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-random
          downstream-url: https://github.com/pulumi/pulumi-random
          use-provider-dir: true
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}

  downstream-kubernetes:
    name: Test Kubernetes Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6277ebec57d2f9283d245d365f0b05bcc23d85e0
        with:
          repo: pulumi/pulumictl

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: pulumi/action-test-provider-downstream@093f43c86c9b4820e1e3c80df8feab04868890f7
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          replacements: github.com/pulumi/pulumi/pkg/v2=pulumi/pkg,github.com/pulumi/pulumi/sdk/v2=pulumi/sdk
          downstream-name: pulumi-kubernetes
          downstream-url: https://github.com/pulumi/pulumi-kubernetes
          use-provider-dir: true
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}
