name: Direct build

on:
  schedule:
  # 1030 UTC every weekday
  - cron: "30 10 * * 1-5"

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Build
        shell: bash
        run: GOPROXY=direct make build
  sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Build
        shell: bash
        run: |
          mkdir test
          cd test
          pulumi new random-go --generate-only --yes
          go mod edit -replace github.com/pulumi/pulumi/sdk/v3=../sdk
          GOPROXY=direct pulumi install
