name: Direct build

on:
  schedule:
  # 1030 UTC every weekday
  - cron: "30 10 * * 1-5"

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.24"
      - name: Build
        shell: bash
        run: GOPROXY=direct SDKS="" make build
  sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.24"

      - uses: pulumi/actions@v6
        with:
          pulumi-version: dev

      - name: Build
        shell: bash
        run: |
          mkdir test
          cd test
          pulumi new random-go --generate-only --yes
          go mod edit -replace github.com/pulumi/pulumi/sdk/v3=../sdk
          GOPROXY=direct pulumi install
