env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  VERSION: ${{ github.event.client_payload.ref }}
  COMMIT_SHA: ${{ github.event.client_payload.commitSha }}

on:
  repository_dispatch:
    types:
      - homebrew-bump

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Add Homebrew to the PATH
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "${GITHUB_PATH}"
      - uses: dawidd6/action-homebrew-bump-formula@c5ddc585e75f0f750a8b4f610688b4bec9e80915 # v6
        with:
          token: ${{secrets.PULUMI_BOT_HOMEBREW_TOKEN}}
          formula: pulumi
          tag: v${{env.VERSION}}
          revision: ${{env.COMMIT_SHA}}
